# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Europe/Berlin"
    labels:
      - "p:continuous-integration"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      # phased updates:
      # - friday: std
      # - saturday: all others
      interval: "weekly"
      day: "saturday"
      time: "18:00"
      timezone: "Europe/Berlin"
    labels:
      - "p:dependencies"
    # Allow only 1 PR because it would open a lot of PRs for each imported module
    # in the reactive-graph workspace if reactive-graph has new commits
    open-pull-requests-limit: 1
    groups:
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
